### PR TITLE
Add myself to the table

### PR DESCRIPTION
**Pull request by phikal**
As a side comment: Is using a table really the that good of an idea? It seems that maintaining a table under version control is prone to create annoyances.

### CODE REVIEW

**Comment by phikal** [comment]
Oh an thank you for pushing this idea.

**Comment by ag91** [comment]
> Is using a table really the that good of an idea? It seems that maintaining a table under version control is prone to create annoyances.

It depends: the initiative is still in its infancy :) So far we had more generous candidate buddies than new users. And yet, the table has not caused conflicts yet XD I guess we would need something like a website if we get some significant throughput, but it seems too early now. Do you have a simpler suggestion to fix this problem?

**Comment by phikal** [comment]
> Do you have a simpler suggestion to fix this problem?

Maybe an unordered list or a description list would also work.

As a  more general point, I wonder if GitHub is the best place for this, compared to something like EmacsWiki.

**Comment by ag91** [comment]
> Maybe an unordered list or a description list would also work

Forgive me, I may have misunderstood: what problem does that solve? Can you give me an example? I thought you meant possible conflicts on PRs, but maybe you meant presentation?

Definitely for EmacsWiki! I was just thinking to advertise the initiative there and maybe I could actually ask if it would makes sense to host it there once it picks up? Who manages that wiki, do you know?

**Comment by phikal** [comment]
> Forgive me, I may have misunderstood: what problem does that solve? Can you give me an example? I thought you meant possible conflicts on PRs, but maybe you meant presentation?

The issue with a table is that if one person needs a wider table (e.g. a longer name or link) then the entire table is redrawn.  If anyone else were to propose another merge request, their commits would conflict one another, as happened to me, despite no substantial content being in conflict.

> Definitely for EmacsWiki! I was just thinking to advertise the initiative there and maybe I could actually ask if it would makes sense to host it there once it picks up? Who manages that wiki, do you know?

Not sure who is currently administrating (probably Alex Schroeder), but that shouldn't matter. We can just pick any unused page, e.g. https://www.emacswiki.org/emacs/EmacsBuddies and translate the README to oddmuse. Then anyone can add themselves to the page, without the need for submitting pull requests.

**Comment by ag91** [comment]
it makes a lot of sense. I will take some time to see if this picks up and then I will act. Thanks for the suggestions!

**Comment by phikal** [comment]
> I will take some time to see if this picks up and then I will act.

Have you put any thought into promoting the information? Could one maybe ping some popular bloggers and vloggers to mention the initiative? Maybe even mention it in the Emacs manual (though in that case I would imagine an EmacsWiki site would be preferred over GitHub)?

**Comment by phikal** [comment]
ping?

**Comment by ag91** [comment]
thanks for the ping! I think that is a good idea: maybe I could ping the people at EmacsConf to share the news? Sacha probably would help us :)

**Comment by yantar92** [comment]
> Maybe even mention it in the Emacs manual

I am not sure if this is the best place. I afraid that the actual newbies will rather look into Emacs-related websites, like emacs.org/orgmode.org/reddit/stackoverflow.

**Comment by phikal** [comment]
ag91 ***@***.***> writes:

> thanks for the ping! I think that is a good idea: maybe I could ping
> the people at EmacsConf to share the news? Sacha probably would help
> us :)

It is still a while until EmacsConf takes place, but I think that Sacha
would bring it up in the Emacs Newsletter.

**Comment by sachac** [comment]
Sure, I can put it in Emacs News. :)

+1 for the unordered list - might be easier to add to, and it could be more readable on mobile devices too.

**Comment by phikal** [comment]
I must confess, I am confused.  Are we talking about the current list on GitHub or about moving the list to Emacs Wiki?

**Comment by sachac** [comment]
A list would probably work on either. Should I hold off on linking to it in Emacs News until people have decided either way?

**Comment by ag91** [comment]
We can use this for now and I can check out with @phikal  for suggestion to integrate with EmacsWiki? The reason I would keep it here for now is so I can still do gatekeeping because I didn't get agreement to just paste emails of people on a public list :)

**Comment by phikal** [comment]
How are the email addresses currently handled?  From what I understand you have a list somewhere, and anyone interested would contact you, asking for the address of XYZ, right?

**Comment by ag91** [comment]
that is correct, I can retrieve those address. I usually give an intro to people looking for buddies so we find the best buddy for them (or I put them in touch with those they are interested in)

**Comment by phikal** [comment]
In that case I misunderstood the system, and switching to Emacs Wiki would not be that easy.  But out of curiosity, how many people have contacted you for a recommendation or to put them in touch with someone?  I am guessing that there might have also been people who just contact the people directly via the "Useful link" (or at least that is what I assumed happened a few days ago when someone sent me a message).

**Comment by ag91** [comment]
I think about 10ish so far went through me. It may be that others skip me and go directly to the buddy, which is fine to me :)

**Pull request merged**
